// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1hD8TCcmTjhoAf4lFMNvs4l2mOG7nvuc',
    appId: '1:52857900101:web:117d55ef78355da900272c',
    messagingSenderId: '52857900101',
    projectId: 'com-apoapp-id998',
    authDomain: 'com-apoapp-id998.firebaseapp.com',
    storageBucket: 'com-apoapp-id998.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPM6GcrNPoKBmrH7eaYkpNRMUp5wYYV9E',
    appId: '1:52857900101:android:e21d39adc213a1b600272c',
    messagingSenderId: '52857900101',
    projectId: 'com-apoapp-id998',
    storageBucket: 'com-apoapp-id998.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNwzBRG5JPYmHUNlquMT6m9rmw7r_Z7Es',
    appId: '1:52857900101:ios:8a444fa2d1357db700272c',
    messagingSenderId: '52857900101',
    projectId: 'com-apoapp-id998',
    storageBucket: 'com-apoapp-id998.firebasestorage.app',
    iosBundleId: 'com.apoapp.id998',
  );
}
